export const API_BASE_URL = 'https://api.websparks.ai'
// export const API_BASE_URL = 'http://20.121.120.240:8000'
export const PRICING_URL = 'https://subscription.websparks.ai'
export const CHAT_URL = 'https://chat.websparks.ai'
export const MAIN_URL = 'https://websparks.ai'